name: CI/CD

on:
  push:
    branches: [main, feat/setup-ci-cd]
  pull_request:
    branches: [main, develop]

jobs:
  # 1er job: validation
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with: { version: 11 }
      - uses: actions/setup-node@v4
        with: { node-version: 24, cache: "pnpm" }
      - run: pnpm install
      - run: pnpm lint # Vérifie le code
      - run: pnpm test # Exécute les tests
      - run: pnpm build # Vérifie que le build React passe

  # 2eme job : construire l'image et l'envoyer sur le registre
  build-and-push:
    needs: quality-check
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # seulement si c'est un push sur main
    runs-on: ubuntu-latest
    permissions: # principe du moindre privilège
      contents: read # lire le code
      packages: write # écrire les packages
    steps:
      - name: Checkout code
        uses: actions/checkout@v6 # récupère le code source pour que la VM y ait accès

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with: { version: 11 }

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4 # Connexion à l'espace de stockage Docker Github
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx # pour pouvoir utiliser le cache gha
        uses: docker/setup-buildx-action@v4

      - name: Build and push Docker image
        uses: docker/build-push-action@v7 # Construit avec le Dockerfile et l'envoie sur ghcr.io
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          cache-from: type=gha # Cache magique GitHub
          cache-to: type=gha,mode=max

  # 3eme job : se connecter au serveur et mettre à jour le container
  deploy:
    needs: build-and-push # attends que le 2eme job soit terminé
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # seulement si c'est un push sur main
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Install cloudflared
        run: |
          curl -fsSL -o cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb
          rm cloudflared.deb

      - name: Configure SSH client
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          CF_ID: ${{ secrets.CF_CLIENT_ID }}
          CF_SECRET: ${{ secrets.CF_CLIENT_SECRET }}
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          cat <<EOF > ~/.ssh/config
          Host $HOST
              User $USER
              IdentityFile ~/.ssh/id_rsa
              StrictHostKeyChecking no
              ProxyCommand cloudflared access ssh --hostname %h --service-token-id $CF_ID --service-token-secret $CF_SECRET
          EOF

      - name: Deploy via SSH
        env:
          DOMAIN_NAME: ${{ secrets.MY_DOMAIN }}
          REPO: ${{ github.repository }}
          HOST: ${{ secrets.SERVER_HOST }}
        run: |
          ssh "$HOST" bash -s <<EOF
            DOMAIN_NAME="$DOMAIN_NAME"
            docker pull ghcr.io/$REPO:latest
            docker stop portfolio || true
            docker rm portfolio || true
            docker run -d \\
              --name portfolio \\
              --restart always \\
              --network gateway \\
              --label "traefik.enable=true" \\
              --label "traefik.http.routers.portfolio.rule=Host(\\\`\$DOMAIN_NAME\\\`)" \\
              --label "traefik.http.routers.portfolio.entrypoints=websecure" \\
              --label "traefik.http.routers.portfolio.tls.certresolver=letsencrypt" \\
              --label "traefik.http.services.portfolio.loadbalancer.server.port=80" \\
              ghcr.io/$REPO:latest
            docker image prune -f
          EOF
